// front-react/src/views/home/Home.jsx
import React, { useState } from 'react'
import './Home.css'

export default (props) => {

  let [legenda, setLegenda] = useState('Estou no React')

  function resetLegenda() {
    console.log('Evento de click no Angular')
    setLegenda('Estou no React')
  }
  
  return (
    <div className="home">
      <h1>Componente Home</h1>
      <h2>{ props.msg }</h2>
      <h3>{ legenda }</h3>
      <input value={legenda} onChange={ e => setLegenda(e.target.value) } />
      <button onClick={resetLegenda}>Reset Legenda</button>
    </div>
  )
}

// front-vue/src/views/home/Home.vue
<template>
  <div>
    <h1>Componente Home</h1>
    <h2>{{ msg }}</h2>
    <h3>{{ legenda }}</h3>
    <input type="text" v-model="legenda"/>
    <button @click="resetLegenda">Reset Legenda</button>
  </div>
</template>

<script>
export default {
  props: ['msg'],
  data: function() {
    return {
      legenda: 'Estou no Vue'
    }
  },
  methods: {
    resetLegenda() {
      this.legenda = 'Estou no Vue'
      console.log('Evento de click no Vue')
    }
  }
}
</script>

<style>

</style>
