// front-react/src/App.js
import React from 'react';
import './App.css';

import Home from './views/home/Home'
import Home2 from './views/home/Home2'

function App() {
  return (
    <div className="App">
     <Home msg="Oi sou o Componente Home passando parametro"></Home>
     <Home2 msg="Oi sou o Componente Home2 passando parametro"></Home2>
    </div>
  );
}

export default App;

// front-vue/src/App.vue
<template>
  <div id="app">
    <Home msg="Oi sou o Componente Home passando parametro"></Home>
  </div>
</template>

<script>
import Home from './views/home/Home'

export default {
  name: 'App',
  components: {
    Home
  }
}
</script>

<style>
#app {
  font-family: Avenir, Helvetica, Arial, sans-serif;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
  text-align: center;
  color: #2c3e50;
  margin-top: 60px;
}
</style>
